# this tells buffanetes the version of the configs in the .buffanetes directory.
# it's to make sure you're using the right CLI to match the configs
version = 1

# this tells buffanetes the default docker repository to use. you can override this on the
# command line though
default-docker-repo = quay.io/tentsk8s/buffanetes

# this tells buffanetes what to call this app! it defines
app-name = "buffanetes"
